### ISSUE TITLE
C binding namespace causes errors in leptos builds

### ISSUE THREAD

**Issue by dominikwilkowski** [elsirion/leptos-qr-scanner#2]
Hi there,

Been trying to use this lib and found when installing it it caused all prog macros to panic. Turns out the C bindings clash with other name spaces (I think it's just the `new` method but could also be the others didn't look too deeply into it).
(I use leptos with SSR and axum)

I fixed it by doing this:
```rust
#[wasm_bindgen]
extern "C" {
	#[derive(Clone, Debug)]
	type QrScanner;

	#[wasm_bindgen(constructor, js_name = new)]
	fn qr_new(
		video_elem: &web_sys::HtmlVideoElement,
		callback: &js_sys::Function,
		options: &JsValue,
	) -> QrScanner;

	#[wasm_bindgen(method, js_name = start)]
	fn qr_start(this: &QrScanner);
	#[wasm_bindgen(method, js_name = stop)]
	fn qr_stop(this: &QrScanner);
	#[wasm_bindgen(method, js_name = destroy)]
	fn qr_destroy(this: &QrScanner);
}
```

Feels like a good work around and a good thing to do in general. I'm happy to submit a PR if you're keen on this.

Another thing I changed in my copy of this repo is co-locating both the js files within my own public folder as to not make a round trip to a CDN. Would be nice as an option perhaps but maybe this is a separate issue.

**Comment by elsirion** [comment]
> Feels like a good work around and a good thing to do in general. I'm happy to submit a PR if you're keen on this.
> 
> Another thing I changed in my copy of this repo is co-locating both the js files within my own public folder as to not make a round trip to a CDN. Would be nice as an option perhaps but maybe this is a separate issue.

Both are great improvements I'd love to merge PRs for, especially the CDN issue was annoying me too!
